/* make_db_tests.js - writes the parity tests that carry fixture rows inside
   them: the HH2 fixture through the RPCs and v_labor_priced must agree with
   expected.json (the same spec app/labor_model.js is held to), and the two
   on-rent snapshots must give the same month figures rentals_model.js does.
   `node tests/db/make_db_tests.js` (tests/db/run.sh calls it) */
"use strict";
const fs = require("fs"), path = require("path");
const HH2 = require("../../app/hh2.js"), OnRent = require("../../app/onrent.js");
const F = path.join(__dirname, "../fixtures");
const out = (rel, s) => fs.writeFileSync(path.join(__dirname, "../../supabase/tests", rel), s);
const WS = "00000000-0000-4000-8000-000000000001";
const EDITOR = `select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000002","email":"editor@example.com","role":"authenticated"}', true);
set local role authenticated;`;
const VIEWER = `select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000003","email":"viewer@example.com","role":"authenticated"}', true);
set local role authenticated;`;
const USERS = `insert into auth.users (id, email) values ('10000000-0000-4000-8000-000000000002', 'editor@example.com'), ('10000000-0000-4000-8000-000000000003', 'viewer@example.com');
insert into public.members (workspace_id, email, user_id, role) values
  ('${WS}', 'editor@example.com', '10000000-0000-4000-8000-000000000002', 'editor'),
  ('${WS}', 'viewer@example.com', '10000000-0000-4000-8000-000000000003', 'viewer');`;
const J = (v) => "$j$" + JSON.stringify(v) + "$j$::jsonb";

// ---- labor --------------------------------------------------------------------------
const X = JSON.parse(fs.readFileSync(path.join(F, "hh2/expected.json"), "utf8"));
const doc = HH2.read(fs.readFileSync(path.join(F, "hh2", X.file)), X.file);
const employees = JSON.parse(fs.readFileSync(path.join(F, "rates/employees.json"), "utf8"));
const ratesJson = JSON.parse(fs.readFileSync(path.join(F, "rates/iowa_fy27.json"), "utf8"));
function fixtureTables() {
  return Object.entries(ratesJson.tables).map(([job, code]) => ({ code, description: "fixture " + job,
    rates: ratesJson.table.filter((r) => !(r.except_tables || []).includes(code)).map((r) => ({ certified_class: r.certified_class, pay_id: r.pay_id, rate_cents: r.rate_cents, effective_from: ratesJson.effective_from, effective_to: ratesJson.effective_to })) }));
}
const fixtureRateCount = () => fixtureTables().reduce((t, x) => t + x.rates.length, 0);
const rows = doc.rows.map((r) => ({ row_index: r.row_index, employee_number: r.employee_number, work_date: r.work_date, payroll_group: r.payroll_group,
  payroll_service_id: r.payroll_service_id, job_number: r.job_number, job_name: r.job_name, child_job: r.child_job, child_job_name: r.child_job_name,
  cost_code: r.cost_code, cost_code_name: r.cost_code_name, pay_type: r.pay_type, pay_type_name: r.pay_type_name, hours_x100: r.hours_x100 }));
const heldReasons = Object.entries(X.heldByReason).map(([k, v]) => `select is((select count(*) from public.v_labor_priced where status = 'held:${k}'), ${v}::bigint, 'held: ${k}');`).join("\n");
out("03_labor_parity.sql", `-- 03_labor_parity.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- The fixture HH2 export, recorded through the RPCs, priced by v_labor_priced,
-- must match expected.json row for row - the same spec app/labor_model.js meets.
begin;
select plan(${14 + Object.keys(X.heldByReason).length});
${USERS}
${EDITOR}
-- the fixture's rate tables come in through the Sage import RPC (one per CDR job; #226021 lacks #LAB-J double time) and FB5003 is a General Foreman
create temp table rt as select (public.begin_upload('${WS}', 'sage_rates', repeat('e', 64), 'rates.xlsx', 100) ->> 'upload_id')::uuid as id;
select public.retire_rate(id) from public.billable_rates where workspace_id = '${WS}';
create temp table imp as select public.import_rate_tables((select id from rt), ${J(fixtureTables())}) as r;
select is((select (r ->> 'inserted')::int from imp), ${fixtureRateCount()}, 'the fixture rate tables import');
insert into public.employees (workspace_id, employee_number, certified_class) values ${Object.entries(employees).map(([n, e]) => `('${WS}', '${n}', '${e.certified_class}')`).join(", ")};
create temp table up as select (public.begin_upload('${WS}', 'hh2_labor', repeat('d', 64), '${X.file}', 12345,
  ${J({ period: X.range, employees: Object.keys(doc.employees), summary: { rows: X.rows } })}) ->> 'upload_id')::uuid as id;
select is(public.append_labor_lines((select id from up), ${J(rows)}), ${X.rows}, 'every fixture row appended');
select is((select public.finalize_upload((select id from up), ${J({ rows: X.rows, hours_x100: X.hoursX100 })}) ->> 'status'), 'recorded', 'conservation holds and it records');
create temp table expected (row_index int, status text, cost_cents bigint);
insert into expected values ${X.rowStatus.map((r) => `(${r.row_index}, '${r.status}', ${r.cost_cents == null ? "null" : r.cost_cents})`).join(", ")};
select is((select count(*) from public.v_labor_priced), ${X.rows}::bigint, 'every row is live');
select is((select count(*) from public.v_labor_priced p join expected e on e.row_index = p.row_index where p.status is distinct from e.status), 0::bigint, 'every status matches the spec');
select is((select count(*) from public.v_labor_priced p join expected e on e.row_index = p.row_index where p.cost_cents is distinct from e.cost_cents), 0::bigint, 'every cost matches the spec');
select is((select coalesce(sum(cost_cents), 0)::bigint from public.v_labor_priced), ${X.costCents}::bigint, 'total cost ${X.costCents}');
select is((select sum(round(hours * 100))::bigint from public.v_labor_priced), ${X.hoursX100}::bigint, 'hours conserved');
${heldReasons}
select is((select count(*) from public.v_labor_priced where status like 'held:%' and cost_cents is not null), 0::bigint, 'held rows carry no cost, never $0');
select is((select cost_cents from public.v_labor_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${X.byJob["50-60-225121"].costCents}::bigint, 'the DC4 September tile');
select is((select week_ending from public.labor_lines where row_index = 2), '2026-09-06'::date, 'week ending is the Sunday on or after');
-- the held rows disappear from the audit once Settings answers
insert into public.employees (workspace_id, employee_number, certified_class) values ('${WS}', 'FE9001', '#LAB-J');
select is((select status from public.v_labor_priced where employee_number = 'FE9001'), 'held:unknown job', 'a class set in Settings still leaves an unknown job held');
reset role;
${VIEWER}
select is((select count(*) from public.v_labor_priced), 0::bigint, 'a viewer sees no lines');
select is((select cost_cents from public.v_labor_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${X.byJob["50-60-225121"].costCents}::bigint, 'but sees the job month aggregate');
reset role;
select * from finish();
rollback;
`);

// ---- rentals -------------------------------------------------------------------------
const R = JSON.parse(fs.readFileSync(path.join(F, "onrent/expected.json"), "utf8"));
const snap = (f) => OnRent.read(fs.readFileSync(path.join(F, "onrent", f)), f);
const wk1 = snap(R.wk1.file), wk2 = snap(R.wk2.file);
const lineRows = (s) => s.lines.map((l) => ({ row_index: l.row_index, equipment_no: l.equipment_no, contract_no: l.contract_no, vendor_job_ref: l.vendor_job_ref, seq: l.seq,
  line_ref: l.line_ref, description: l.description, qty: l.qty, on_rent_date: l.on_rent_date, rate_period: l.rate_period, rate_cents: l.rate_cents, monthly_rent_cents: l.monthly_rent_cents,
  day_rate_cents: l.day_rate_cents, week_rate_cents: l.week_rate_cents, fourweek_rate_cents: l.fourweek_rate_cents, month_rate_cents: l.month_rate_cents,
  po: l.po, est_return: l.est_return, billed_through: l.billed_through, pickup_date: l.pickup_date, liberty_owned: l.liberty_owned, cost_code: l.cost_code, raw: l.raw }));
// the same day again, with only DC4's lines: the report recorded last stands for the month
const wk2bLines = wk2.lines.filter((l) => l.vendor_job_ref === "CDR DC4");
const wk2b = Object.assign({}, wk2, { fileName: "sunbelt_2026-09-26_later.csv", lines: wk2bLines, totals: Object.assign({}, wk2.totals, { lines: wk2bLines.length, rent_cents: wk2bLines.reduce((t, l) => t + (l.monthly_rent_cents || 0), 0) }) });
const record = (name, s, sha) => `create temp table ${name} as select (public.begin_upload('${WS}', 'onrent', repeat('${sha}', 64), '${s.fileName}', 1000,
  ${J({ vendor_key: s.vendor_key, as_of: s.as_of })}) ->> 'upload_id')::uuid as id;
select is(public.append_onrent_lines((select id from ${name}), ${J({ vendor_key: s.vendor_key, layout: s.layout, as_of: s.as_of })}, ${J(lineRows(s))}), ${s.lines.length}, '${s.fileName}: lines appended');
select is((select public.finalize_upload((select id from ${name}), ${J({ lines: s.totals.lines, rent_cents: s.totals.rent_cents })}) ->> 'status'), 'recorded', '${s.fileName}: recorded');`;
out("04_rentals_parity.sql", `-- 04_rentals_parity.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- Two Sunbelt snapshots a week apart: the month's figures and the off-rent
-- item must be what rentals_model.js computes.
begin;
select plan(18);
${USERS}
${EDITOR}
select public.map_vendor_job('${WS}', 'sunbelt', 'CDR DC4', '50-60-225121');
select public.map_vendor_job('${WS}', 'sunbelt', 'CDR DC5', '50-60-225120');
${record("s1", wk1, "e")}
${record("s2", wk2, "f")}
select is((select rent_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.rent}::bigint, 'DC4 September rent at the latest snapshot');
select is((select tax_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.tax}::bigint, 'tax 7%');
select is((select markup_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.markup}::bigint, 'markup 10% on rent plus tax');
select is((select total_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.total}::bigint, 'total to the client');
select is((select total_cents from public.v_rental_month where job_number = '50-60-225120' and month = '2026-09-01'), ${R.dc5_wk2.total}::bigint, 'DC5 too');
select is((select off_rent_date from public.v_rental_items where equipment_no = '1005'), '${wk2.as_of}'::date, 'the item missing from the later report went off rent on its day');
select is((select first_seen from public.v_rental_items where equipment_no = '1006'), '${wk2.as_of}'::date, 'the new item is first seen on the later report');
select is((select job_number from public.v_rental_items where equipment_no = '1005'), null::text, 'an unmapped vendor job name has no job');
select is((select rental_cents from public.v_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.total}::bigint, 'the job month tile carries the client total');
select is((select cents from public.v_month_buckets where job_number = '50-60-225121' and month = '2026-09-01' and bucket = 'EQUIPMENT'), ${R.dc4_wk2.total}::bigint, 'and the GRforecast bucket');
${record("s3", wk2b, "a")}
select is((select count(*) from public.v_rental_month where job_number = '50-60-225120' and month = '2026-09-01' and vendor_key = 'sunbelt'), 0::bigint, 'a second report as of the same day, recorded last, stands for the month: DC5 is not on it');
select is((select rent_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.rent}::bigint, 'DC4 is, at the same rent');
reset role;
select * from finish();
rollback;
`);
// ---- purchases -------------------------------------------------------------------------
const PO = require("../../app/purchase_pro.js");
const PX = JSON.parse(fs.readFileSync(path.join(F, "purchases/expected.json"), "utf8"));
const pdoc = PO.read(fs.readFileSync(path.join(F, "purchases", PX.file)), PX.file);
const poRows = pdoc.pos.map((p) => ({ row_index: p.row_index, po_number: p.po_number, order_date: p.order_date, order_type: p.order_type, supplier_code: p.supplier_code, supplier_name: p.supplier_name,
  job_number: p.job_number, description: p.description, bucket: p.bucket, cancelled: p.cancelled, quote: p.quote, committed_cents: p.committed_cents, raw: p.raw }));
out("05_purchases.sql", `-- 05_purchases.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- The Purchase Pro export through the RPCs: what counts, what waits, and that
-- the latest export replaces the one before.
begin;
select plan(11);
${USERS}
${EDITOR}
create temp table p1 as select (public.begin_upload('${WS}', 'purchase_orders', repeat('a1', 32), '${PX.file}', 1000, ${J({ as_of: pdoc.as_of })}) ->> 'upload_id')::uuid as id;
select is(public.append_purchase_orders((select id from p1), ${J(poRows)}), ${PX.pos}, 'every PO appended');
select is((select public.finalize_upload((select id from p1), ${J({ pos: PX.pos, committed_cents: PX.committed_cents })}) ->> 'status'), 'recorded', 'conservation holds and it records');
select is((select count(*) from public.v_purchase_docs), ${PX.pos}::bigint, 'every PO is live');
select is((select status from public.v_purchase_docs where doc_number = 'Q-26-011098'), 'excluded', 'a quote is excluded');
select is((select status from public.v_purchase_docs where doc_number = '26-011097'), 'excluded', 'a cancelled PO is excluded');
select is((select status from public.v_purchase_docs where doc_number = '26-011094'), 'needs_decision', 'no committed amount yet waits');
select is((select status from public.v_purchase_docs where doc_number = '26-011092'), 'needs_decision', 'a job not in Settings waits');
select is((select sum(amount_cents)::bigint from public.v_purchase_month where job_number = '50-60-225121' and month = '2026-09-01' and status = 'auto'), ${PX.dc4Sep}::bigint, 'DC4 September committed');
select is((select bucket from public.v_purchase_month where job_number = '50-60-225121' and month = '2026-09-01' and status = 'auto'), 'NON_BILLABLE'::app.bucket, 'and it is non-billable, as the description says');
select is((select purchase_cents from public.v_job_month where job_number = '50-60-225120' and month = '2026-09-01'), ${PX.dc5Sep}::bigint, 'the DC5 tile carries its committed material');
-- a later export replaces the earlier one
create temp table p2 as select (public.begin_upload('${WS}', 'purchase_orders', repeat('b2', 32), 'Tbl_PO1_2026-10-02.xlsx', 1000, ${J({ as_of: "2026-10-02" })}) ->> 'upload_id')::uuid as id;
select public.append_purchase_orders((select id from p2), ${J(poRows.slice(0, 2))});
select public.finalize_upload((select id from p2), ${J({ pos: 2, committed_cents: 31250 })});
select is((select count(*) from public.v_purchase_docs), 2::bigint, 'the latest export stands for every PO; the earlier one is history');
reset role;
select * from finish();
rollback;
`);
console.log("wrote supabase/tests/03_labor_parity.sql, 04_rentals_parity.sql and 05_purchases.sql");
