/* make_db_tests.js - writes the parity tests that carry fixture rows inside
   them: the HH2 fixture through the RPCs and v_labor_priced must agree with
   expected.json (the same spec app/labor_model.js is held to), and the two
   on-rent snapshots must give the same month figures rentals_model.js does.
   `node tests/db/make_db_tests.js` (tests/db/run.sh calls it) */
"use strict";
const fs = require("fs"), path = require("path");
const HH2 = require("../../app/hh2.js"), OnRent = require("../../app/onrent.js");
const F = path.join(__dirname, "../fixtures");
const out = (rel, s) => fs.writeFileSync(path.join(__dirname, "../../supabase/tests", rel), s);
const WS = "00000000-0000-4000-8000-000000000001";
const EDITOR = `select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000002","email":"editor@example.com","role":"authenticated"}', true);
set local role authenticated;`;
const VIEWER = `select set_config('request.jwt.claims', '{"sub":"10000000-0000-4000-8000-000000000003","email":"viewer@example.com","role":"authenticated"}', true);
set local role authenticated;`;
const USERS = `insert into auth.users (id, email) values ('10000000-0000-4000-8000-000000000002', 'editor@example.com'), ('10000000-0000-4000-8000-000000000003', 'viewer@example.com');
insert into public.members (workspace_id, email, user_id, role) values
  ('${WS}', 'editor@example.com', '10000000-0000-4000-8000-000000000002', 'editor'),
  ('${WS}', 'viewer@example.com', '10000000-0000-4000-8000-000000000003', 'viewer');`;
const J = (v) => "$j$" + JSON.stringify(v) + "$j$::jsonb";

// ---- labor --------------------------------------------------------------------------
const X = JSON.parse(fs.readFileSync(path.join(F, "hh2/expected.json"), "utf8"));
const doc = HH2.read(fs.readFileSync(path.join(F, "hh2", X.file)), X.file);
const employees = JSON.parse(fs.readFileSync(path.join(F, "rates/employees.json"), "utf8"));
const WX = JSON.parse(fs.readFileSync(path.join(F, "hh2/weekly_expected.json"), "utf8"));
const wdoc = HH2.read(fs.readFileSync(path.join(F, "hh2", WX.file)), WX.file);
const ratesJson = JSON.parse(fs.readFileSync(path.join(F, "rates/iowa_fy27.json"), "utf8"));
function fixtureTables() {
  return Object.entries(ratesJson.tables).map(([job, code]) => ({ code, description: "fixture " + job,
    rates: ratesJson.table.filter((r) => !(r.except_tables || []).includes(code)).map((r) => ({ certified_class: r.certified_class, pay_id: r.pay_id, rate_cents: r.rate_cents, effective_from: ratesJson.effective_from, effective_to: ratesJson.effective_to })) }));
}
const fixtureRateCount = () => fixtureTables().reduce((t, x) => t + x.rates.length, 0);
const rows = doc.rows.map((r) => ({ row_index: r.row_index, employee_number: r.employee_number, work_date: r.work_date, payroll_group: r.payroll_group,
  payroll_service_id: r.payroll_service_id, job_number: r.job_number, job_name: r.job_name, child_job: r.child_job, child_job_name: r.child_job_name,
  cost_code: r.cost_code, cost_code_name: r.cost_code_name, pay_type: r.pay_type, pay_type_name: r.pay_type_name, hours_x100: r.hours_x100 }));
const heldReasons = Object.entries(X.heldByReason).map(([k, v]) => `select is((select count(*) from public.v_labor_priced where status = 'held:${k}'), ${v}::bigint, 'held: ${k}');`).join("\n");
out("03_labor_parity.sql", `-- 03_labor_parity.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- The fixture HH2 export, recorded through the RPCs, priced by v_labor_priced,
-- must match expected.json row for row - the same spec app/labor_model.js meets.
begin;
select plan(${23 + Object.keys(X.heldByReason).length});
${USERS}
${EDITOR}
-- the fixture's rate tables come in through the Sage import RPC (one per CDR job; #226021 lacks #LAB-J double time) and FB5003 is a General Foreman
create temp table rt as select (public.begin_upload('${WS}', 'sage_rates', repeat('e', 64), 'rates.xlsx', 100) ->> 'upload_id')::uuid as id;
select public.retire_rate(id) from public.billable_rates where workspace_id = '${WS}';
create temp table imp as select public.import_rate_tables((select id from rt), ${J(fixtureTables())}) as r;
select is((select (r ->> 'inserted')::int from imp), ${fixtureRateCount()}, 'the fixture rate tables import');
insert into public.employees (workspace_id, employee_number, certified_class) values ${Object.entries(employees).map(([n, e]) => `('${WS}', '${n}', '${e.certified_class}')`).join(", ")};
create temp table up as select (public.begin_upload('${WS}', 'hh2_labor', repeat('d', 64), '${X.file}', 12345,
  ${J({ period: X.range, employees: Object.keys(doc.employees), summary: { rows: X.rows } })}) ->> 'upload_id')::uuid as id;
select is(public.append_labor_lines((select id from up), ${J(rows)}), ${X.rows}, 'every fixture row appended');
select is((select public.finalize_upload((select id from up), ${J({ rows: X.rows, hours_x100: X.hoursX100 })}) ->> 'status'), 'recorded', 'conservation holds and it records');
create temp table expected (row_index int, status text, cost_cents bigint);
insert into expected values ${X.rowStatus.map((r) => `(${r.row_index}, '${r.status}', ${r.cost_cents == null ? "null" : r.cost_cents})`).join(", ")};
select is((select count(*) from public.v_labor_priced), ${X.rows}::bigint, 'every row is live');
select is((select count(*) from public.v_labor_priced p join expected e on e.row_index = p.row_index where p.status is distinct from e.status), 0::bigint, 'every status matches the spec');
select is((select count(*) from public.v_labor_priced p join expected e on e.row_index = p.row_index where p.cost_cents is distinct from e.cost_cents), 0::bigint, 'every cost matches the spec');
select is((select coalesce(sum(cost_cents), 0)::bigint from public.v_labor_priced), ${X.costCents}::bigint, 'total cost ${X.costCents}');
select is((select sum(round(hours * 100))::bigint from public.v_labor_priced), ${X.hoursX100}::bigint, 'hours conserved');
${heldReasons}
select is((select count(*) from public.v_labor_priced where status like 'held:%' and cost_cents is not null), 0::bigint, 'held rows carry no cost, never $0');
select is((select cost_cents from public.v_labor_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${X.byJob["50-60-225121"].costCents}::bigint, 'the DC4 September tile');
select is((select week_ending from public.labor_lines where row_index = 2), '2026-09-06'::date, 'week ending is the Sunday on or after');
-- the held rows disappear from the audit once Settings answers
insert into public.employees (workspace_id, employee_number, certified_class) values ('${WS}', 'FE9001', '#LAB-J');
select is((select status from public.v_labor_priced where employee_number = 'FE9001'), 'held:unknown job', 'a class set in Settings still leaves an unknown job held');
-- the prefix defaults are a setting: take FB7's away and the carpenters it covered are held, put it back and they price again
select is((select count(*) from public.prefix_classes where workspace_id = '${WS}'), 5::bigint, 'the workspace was seeded with the five prefix defaults');
delete from public.prefix_classes where workspace_id = '${WS}' and prefix = 'FB7';
select is((select count(*) from public.v_labor_priced where employee_number like 'FB7%' and status = 'held:no class'), ${X.rowStatus.filter((r) => r.employee_number.startsWith("FB7")).length}::bigint, 'without the FB7 default its rows are held: no class');
insert into public.prefix_classes (workspace_id, prefix, certified_class) values ('${WS}', 'FB7', '#CARP-J');
select is((select count(*) from public.v_labor_priced where employee_number like 'FB7%' and status = 'priced'), ${X.rowStatus.filter((r) => r.employee_number.startsWith("FB7")).length}::bigint, 'with it back they price again');
-- the weekly cost workbook's labor history: rows carry the old workbook's cost and are priced at it, with the class they carried
insert into public.jobs (workspace_id, job_number, short_name) values ('${WS}', '${WX.newJob}', '${WX.newJobName}');
create temp table wh as select (public.begin_upload('${WS}', 'hh2_labor', repeat('9', 64), '${WX.file}', 5000,
  ${J({ period: wdoc.range, employees: Object.keys(wdoc.employees), summary: { rows: wdoc.totals.rows, hours_x100: wdoc.totals.hoursX100, layout: "weeklycostdata" } })}) ->> 'upload_id')::uuid as id;
select is(public.append_labor_lines((select id from wh), ${J(wdoc.rows)}), ${wdoc.totals.rows}, 'the history rows appended');
select is((select public.finalize_upload((select id from wh), ${J({ rows: wdoc.totals.rows, hours_x100: wdoc.totals.hoursX100 })}) ->> 'status'), 'recorded', 'the history records');
select is((select coalesce(sum(cost_cents), 0)::bigint from public.v_labor_priced where price_source = 'given'), ${WX.costGivenCents}::bigint, 'rows with the workbook''s cost are priced at it');
select is((select count(*) from public.v_labor_priced where price_source = 'given' and status = 'priced'), ${WX.rowsGiven}::bigint, 'all of them');
select is((select certified_class from public.v_labor_priced where employee_number = 'FB82001' limit 1), '#CARP-F', 'the class the workbook carried stands on those rows');
select is((select count(*) from public.v_labor_priced where source_layout = 'weeklycostdata' and status = 'held:PTO pay type'), ${WX.auditRows}::bigint, 'the audit sheet''s PTO rows are held');
reset role;
${VIEWER}
select is((select count(*) from public.v_labor_priced), 0::bigint, 'a viewer sees no lines');
select is((select cost_cents from public.v_labor_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${X.byJob["50-60-225121"].costCents}::bigint, 'but sees the job month aggregate');
reset role;
select * from finish();
rollback;
`);

// ---- rentals -------------------------------------------------------------------------
const R = JSON.parse(fs.readFileSync(path.join(F, "onrent/expected.json"), "utf8"));
const snap = (f) => OnRent.read(fs.readFileSync(path.join(F, "onrent", f)), f);
const wk1 = snap(R.wk1.file), wk2 = snap(R.wk2.file);
const lineRows = (s) => s.lines.map((l) => ({ row_index: l.row_index, equipment_no: l.equipment_no, contract_no: l.contract_no, vendor_job_ref: l.vendor_job_ref, seq: l.seq,
  line_ref: l.line_ref, description: l.description, qty: l.qty, on_rent_date: l.on_rent_date, rate_period: l.rate_period, rate_cents: l.rate_cents, monthly_rent_cents: l.monthly_rent_cents,
  day_rate_cents: l.day_rate_cents, week_rate_cents: l.week_rate_cents, fourweek_rate_cents: l.fourweek_rate_cents, month_rate_cents: l.month_rate_cents,
  po: l.po, est_return: l.est_return, billed_through: l.billed_through, pickup_date: l.pickup_date, liberty_owned: l.liberty_owned, cost_code: l.cost_code, raw: l.raw }));
// the same day again, with only DC4's lines: the report recorded last stands for the month
const wk2bLines = wk2.lines.filter((l) => l.vendor_job_ref === "CDR DC4");
const wk2b = Object.assign({}, wk2, { fileName: "sunbelt_2026-09-26_later.csv", lines: wk2bLines, totals: Object.assign({}, wk2.totals, { lines: wk2bLines.length, rent_cents: wk2bLines.reduce((t, l) => t + (l.monthly_rent_cents || 0), 0) }) });
// a vendor whose first report comes a day after the month's end (Herc, report date 2026-10-01), and one whose first comes nine days after (too late)
const hercDoc = snap(R.herc.file);
const lateDoc = OnRent.read(fs.readFileSync(path.join(F, "onrent", R.mcw.file)), R.mcw.file, { as_of: "2026-10-09" });
const record = (name, s, sha) => `create temp table ${name} as select (public.begin_upload('${WS}', 'onrent', repeat('${sha}', 64), '${s.fileName}', 1000,
  ${J({ vendor_key: s.vendor_key, as_of: s.as_of })}) ->> 'upload_id')::uuid as id;
select is(public.append_onrent_lines((select id from ${name}), ${J({ vendor_key: s.vendor_key, layout: s.layout, as_of: s.as_of })}, ${J(lineRows(s))}), ${s.lines.length}, '${s.fileName}: lines appended');
select is((select public.finalize_upload((select id from ${name}), ${J({ lines: s.totals.lines, rent_cents: s.totals.rent_cents })}) ->> 'status'), 'recorded', '${s.fileName}: recorded');`;
out("04_rentals_parity.sql", `-- 04_rentals_parity.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- Two Sunbelt snapshots a week apart: the month's figures and the off-rent
-- item must be what rentals_model.js computes.
begin;
select plan(25);
${USERS}
${EDITOR}
select public.map_vendor_job('${WS}', 'sunbelt', 'CDR DC4', '50-60-225121');
select public.map_vendor_job('${WS}', 'sunbelt', 'CDR DC5', '50-60-225120');
${record("s1", wk1, "e")}
${record("s2", wk2, "f")}
select is((select rent_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.rent}::bigint, 'DC4 September rent at the latest snapshot');
select is((select tax_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.tax}::bigint, 'tax 7%');
select is((select markup_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.markup}::bigint, 'markup 10% on rent plus tax');
select is((select total_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.total}::bigint, 'total to the client');
select is((select total_cents from public.v_rental_month where job_number = '50-60-225120' and month = '2026-09-01'), ${R.dc5_wk2.total}::bigint, 'DC5 too');
select is((select off_rent_date from public.v_rental_items where equipment_no = '1005'), '${wk2.as_of}'::date, 'the item missing from the later report went off rent on its day');
select is((select first_seen from public.v_rental_items where equipment_no = '1006'), '${wk2.as_of}'::date, 'the new item is first seen on the later report');
select is((select job_number from public.v_rental_items where equipment_no = '1005'), null::text, 'an unmapped vendor job name has no job');
select is((select rental_cents from public.v_job_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.total}::bigint, 'the job month tile carries the client total');
select is((select cents from public.v_month_buckets where job_number = '50-60-225121' and month = '2026-09-01' and bucket = 'EQUIPMENT'), ${R.dc4_wk2.total}::bigint, 'and the GRforecast bucket');
${record("s3", wk2b, "a")}
select is((select count(*) from public.v_rental_month where job_number = '50-60-225120' and month = '2026-09-01' and vendor_key = 'sunbelt'), 0::bigint, 'a second report as of the same day, recorded last, stands for the month: DC5 is not on it');
-- a month with no report by its end takes the first report after it, within a week
${record("s4", hercDoc, "b")}
select is((select count(*) from public.v_rental_month where vendor_key = 'herc' and month = '2026-09-01'), 1::bigint, 'September takes the Herc report of October 1, the first after the month');
select is((select as_of from public.v_rental_month where vendor_key = 'herc' and month = '2026-09-01' limit 1), '${hercDoc.as_of}'::date, 'and says which day it is as of');
${record("s5", lateDoc, "c")}
select is((select count(*) from public.v_rental_month where vendor_key = 'mcw' and month = '2026-09-01'), 0::bigint, 'nine days after the month is too late');
select is((select rent_cents from public.v_rental_month where job_number = '50-60-225121' and month = '2026-09-01'), ${R.dc4_wk2.rent}::bigint, 'DC4 is, at the same rent');
reset role;
select * from finish();
rollback;
`);
// ---- purchases -------------------------------------------------------------------------
const PO = require("../../app/purchase_pro.js");
const PX = JSON.parse(fs.readFileSync(path.join(F, "purchases/expected.json"), "utf8"));
const pdoc = PO.read(fs.readFileSync(path.join(F, "purchases", PX.file)), PX.file);
const poRows = pdoc.pos.map((p) => ({ row_index: p.row_index, po_number: p.po_number, order_date: p.order_date, order_type: p.order_type, supplier_code: p.supplier_code, supplier_name: p.supplier_name,
  job_number: p.job_number, description: p.description, bucket: p.bucket, cancelled: p.cancelled, quote: p.quote, committed_cents: p.committed_cents, raw: p.raw }));
const unk = pdoc.pos.find((p) => p.po_number === "26-011092"), unkMonth = unk.order_date.slice(0, 7) + "-01";
const unkExpect = (unkMonth === "2026-09-01" ? PX.dc4Sep : 0) + unk.committed_cents;
const pair = poRows.filter((p) => p.po_number === "26-011092" || p.po_number === "26-011094");
const pairCommitted = pair.reduce((t, p) => t + (p.quote || p.cancelled || p.committed_cents == null ? 0 : p.committed_cents), 0);
out("05_purchases.sql", `-- 05_purchases.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- The Purchase Pro export through the RPCs: what counts, what waits, what a
-- decision does, and that the latest export replaces the one before while
-- the decisions, being about the PO, hold.
begin;
select plan(23);
${USERS}
${EDITOR}
create temp table p1 as select (public.begin_upload('${WS}', 'purchase_orders', repeat('a1', 32), '${PX.file}', 1000, ${J({ as_of: pdoc.as_of })}) ->> 'upload_id')::uuid as id;
select is(public.append_purchase_orders((select id from p1), ${J(poRows)}), ${PX.pos}, 'every PO appended');
select is((select public.finalize_upload((select id from p1), ${J({ pos: PX.pos, committed_cents: PX.committed_cents })}) ->> 'status'), 'recorded', 'conservation holds and it records');
select is((select count(*) from public.v_purchase_docs), ${PX.pos}::bigint, 'every PO is live');
select is((select status from public.v_purchase_docs where doc_number = 'Q-26-011098'), 'excluded', 'a quote is excluded');
select is((select status from public.v_purchase_docs where doc_number = '26-011097'), 'excluded', 'a cancelled PO is excluded');
select is((select status from public.v_purchase_docs where doc_number = '26-011094'), 'needs_decision', 'no committed amount yet waits');
select is((select status from public.v_purchase_docs where doc_number = '26-011092'), 'needs_decision', 'a job not in Settings waits');
select is((select status from public.v_purchase_docs where doc_number = '26-011090'), 'needs_decision', 'a live PO with no job waits');
select is((select status from public.v_purchase_docs where doc_number = 'Q-26-011091'), 'excluded', 'a quote with no job is just a quote');
select is((select count(*) from public.v_purchase_docs where doc_number = '26.01' and status = 'needs_decision' and shared_number = 2), 2::bigint, 'a PO number on two orders: both wait, both marked');
select is((select sum(amount_cents)::bigint from public.v_purchase_month where job_number = '50-60-225121' and month = '2026-09-01' and status = 'auto'), ${PX.dc4Sep}::bigint, 'DC4 September committed');
select is((select bucket from public.v_purchase_month where job_number = '50-60-225121' and month = '2026-09-01' and status = 'auto'), 'NON_BILLABLE'::app.bucket, 'and it is non-billable, as the description says');
select is((select purchase_cents from public.v_job_month where job_number = '50-60-225120' and month = '2026-09-01'), ${PX.dc5Sep}::bigint, 'the DC5 tile carries its committed material');
-- decisions: count the unknown-job PO on DC4, leave the no-amount one out
insert into public.purchase_decisions (workspace_id, doc_id, job_number, bucket, decision, reason)
  select workspace_id, id, '50-60-225121', 'MATERIALS', 'assign', 'it is DC4''s' from public.v_purchase_docs where doc_number = '26-011092';
insert into public.purchase_decisions (workspace_id, doc_id, decision, reason)
  select workspace_id, id, 'exclude', 'never priced' from public.v_purchase_docs where doc_number = '26-011094';
select is((select status from public.v_purchase_docs where doc_number = '26-011092'), 'confirmed', 'assigned to a job, the PO counts');
select is((select coalesce(sum(amount_cents), 0)::bigint from public.v_purchase_month where job_number = '50-60-225121' and month = '${unkMonth}' and status in ('auto', 'confirmed')), ${unkExpect}::bigint, 'on that job, in its month');
select is((select status from public.v_purchase_docs where doc_number = '26-011094'), 'excluded', 'left out, with a reason');
insert into public.purchase_decisions (workspace_id, doc_id, job_number, bucket, decision, reason)
  select workspace_id, id, '50-60-225121', 'MATERIALS', 'assign', 'gloves for DC4' from public.v_purchase_docs where doc_number = '26-011090';
select is((select status from public.v_purchase_docs where doc_number = '26-011090'), 'confirmed', 'given a job, the PO with no job counts');
-- a decision on a shared number is about one order: by its OrderID
insert into public.purchase_decisions (workspace_id, doc_id, job_number, bucket, decision, reason)
  select workspace_id, id, '50-60-225121', 'EQUIPMENT', 'confirm', 'the DC4 light tower' from public.v_purchase_docs where doc_number = '26.01' and order_id = '11089';
select is((select status from public.v_purchase_docs where doc_number = '26.01' and order_id = '11089'), 'confirmed', 'the decided order counts');
select is((select status from public.v_purchase_docs where doc_number = '26.01' and order_id = '11088'), 'needs_decision', 'the other order with that number still waits');
-- a later export replaces the earlier one; the decisions hold, being about the PO number
create temp table p2 as select (public.begin_upload('${WS}', 'purchase_orders', repeat('b2', 32), 'Tbl_PO1_2026-10-02.xlsx', 1000, ${J({ as_of: "2026-10-02" })}) ->> 'upload_id')::uuid as id;
select public.append_purchase_orders((select id from p2), ${J(pair)});
select public.finalize_upload((select id from p2), ${J({ pos: pair.length, committed_cents: pairCommitted })});
select is((select count(*) from public.v_purchase_docs), ${pair.length}::bigint, 'the latest export stands for every PO; the earlier one is history');
select is((select status from public.v_purchase_docs where doc_number = '26-011092'), 'confirmed', 'the decision carried to the new export''s copy of the PO');
select is((select status from public.v_purchase_docs where doc_number = '26-011094'), 'excluded', 'and so did the exclusion');
-- the same number on a re-exported order carries only to the same OrderID
create temp table p3 as select (public.begin_upload('${WS}', 'purchase_orders', repeat('c3', 32), 'Tbl_PO1_2026-10-09.xlsx', 1000, ${J({ as_of: "2026-10-09" })}) ->> 'upload_id')::uuid as id;
select public.append_purchase_orders((select id from p3), ${J(poRows.filter((p) => p.po_number === "26.01"))});
select public.finalize_upload((select id from p3), ${J({ pos: 2, committed_cents: 120000 })});
select is((select status from public.v_purchase_docs where doc_number = '26.01' and order_id = '11089'), 'confirmed', 'the decision followed its order into the next export');
reset role;
select * from finish();
rollback;
`);
// ---- the Job Cost To Date and its recurring charges -----------------------------------
const JCTD = require("../../app/jctd.js");
const JX = JSON.parse(fs.readFileSync(path.join(F, "jctd/expected.json"), "utf8"));
const jdoc = JCTD.read(fs.readFileSync(path.join(F, "jctd", JX.file)), JX.file);
const jRows = jdoc.rows.map((r) => ({ row_index: r.row_index, job_number: r.job_number, cost_code: r.cost_code, cost_code_name: r.cost_code_name, cat: r.cat, trans_type: r.trans_type,
  period_end: r.period_end, trans_date: r.trans_date, acct_date: r.acct_date, date_stamp: r.date_stamp, units: r.units, unit_cost_cents: r.unit_cost_cents, amount_cents: r.amount_cents,
  pay_id: r.pay_id, employee_number: r.employee_number, batch: r.batch, vendor_code: r.vendor_code, vendor_name: r.vendor_name, invoice: r.invoice, item: r.item, description: r.description }));
const candRows = JX.candidates.map(([name, amt, units, months, on_feed, lo, current]) => `('${name.replace(/'/g, "''")}', ${amt}, ${units}, ${amt * units}, '${months.join(",")}', ${on_feed}, ${lo}, ${current})`).join(",\n    ");
const mob = JX.candidates[0], mobMonthly = mob[1] * mob[2], mobTotal = mobMonthly + Math.round(mobMonthly * 1000 / 10000);
const two = jRows.slice(0, 2);
out("06_jctd.sql", `-- 06_jctd.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- The JCTD fixture through the RPCs; the recurring charges the SQL finds must
-- be the ones app/recurring_model.js finds; confirming and setting aside; the
-- latest export per job stands; a viewer never reads a line.
begin;
select plan(17);
${USERS}
${EDITOR}
create temp table j1 as select (public.begin_upload('${WS}', 'jctd', repeat('c3', 32), '${JX.file}', 1000,
  ${J({ period: jdoc.range, as_of: jdoc.as_of, summary: { job_number: jdoc.job_number, rows: JX.rows, amount_cents: JX.amount_cents } })}) ->> 'upload_id')::uuid as id;
select is(public.append_jctd_lines((select id from j1), ${J(jRows)}), ${JX.rows}, 'every row appended');
select is((select public.finalize_upload((select id from j1), ${J({ rows: JX.rows, amount_cents: JX.amount_cents })}) ->> 'status'), 'recorded', 'the recount holds and it records');
select is((select count(*) from public.jctd_lines), ${JX.rows}::bigint, 'lines on file');
select is((select count(*) from public.jctd_lines where trans_type = 'PR cost' and description <> ''), 0::bigint, 'payroll lines carry no name');
create temp table want (vendor_name text, amount_cents bigint, units int, monthly_cents bigint, months text, on_feed boolean, liberty_owned boolean, current boolean);
insert into want values
    ${candRows};
select is((select count(*) from public.v_recurring_candidates), ${JX.candidates.length}::bigint, '${JX.candidates.length} recurring charges');
select is((select count(*) from want w join public.v_recurring_candidates c on c.vendor_name = w.vendor_name and c.amount_cents = w.amount_cents and c.units = w.units
  and c.monthly_cents = w.monthly_cents and array_to_string(c.months, ',') = w.months and c.on_feed = w.on_feed and c.liberty_owned = w.liberty_owned and c.current = w.current),
  ${JX.candidates.length}::bigint, 'each one is what the JS model finds: vendor, amount, units, months, feed, Liberty-owned, current');
select is(app.norm_desc('(Rev)26-004809'), '26-004809', 'norm_desc strips the reversal prefix');
select is(app.norm_desc('POLARIS RANGER C~1M03/29-04/25'), 'POLARIS RANGER C~1M', 'and a billing span');
select is(app.norm_desc(' cdr  dc4 7/1-7/31/26'), 'CDR DC4', 'and dates, spaces and case');
-- confirm the contract minimum as a monthly rental from the month it was first seen
insert into public.recurring_charges (workspace_id, job_number, candidate_key, vendor_code, vendor_name, description, cost_code, monthly_cents, units, liberty_owned, amount_includes_tax, start_month)
  select workspace_id, job_number, key, vendor_code, vendor_name, description, cost_code, monthly_cents, units, liberty_owned, true, first_month from public.v_recurring_candidates where vendor_code = 'MOB200';
select is((select count(*) from public.v_recurring_candidates), ${JX.candidates.length - 1}::bigint, 'a confirmed charge leaves the candidates');
select is((select total_cents from public.v_recurring_month where job_number = '${JX.job}' and month = '2026-08-01'), ${mobTotal}::bigint, 'August: the amount plus the job''s 10% markup, no tax added (the invoice carries it)');
select is((select offfeed_cents from public.v_job_month where job_number = '${JX.job}' and month = '2026-08-01'), ${mobTotal}::bigint, 'the job month tile carries it as an off-feed rental');
select is((select sum(cents)::bigint from public.v_month_buckets where job_number = '${JX.job}' and month = '2026-08-01' and bucket = 'EQUIPMENT'), ${mobTotal}::bigint, 'and the GRforecast bucket');
insert into public.recurring_dismissals (workspace_id, job_number, candidate_key, reason)
  select workspace_id, job_number, key, 'the dealer bills it through the PO' from public.v_recurring_candidates where vendor_code = 'ALT100';
select is((select count(*) from public.v_recurring_candidates), ${JX.candidates.length - 2}::bigint, 'a charge set aside leaves them too');
${VIEWER}
select is((select count(*) from public.jctd_lines), 0::bigint, 'a viewer reads no JCTD line');
select is((select count(*) from public.v_recurring_candidates), ${JX.candidates.length - 2}::bigint, 'but sees the candidates');
${EDITOR}
create temp table j2 as select (public.begin_upload('${WS}', 'jctd', repeat('d4', 32), 'CDR_DC4_10-06-26.xlsx', 1000,
  ${J({ period: jdoc.range, as_of: "2026-10-06", summary: { job_number: jdoc.job_number, rows: 2, amount_cents: two[0].amount_cents + two[1].amount_cents } })}) ->> 'upload_id')::uuid as id;
select public.append_jctd_lines((select id from j2), ${J(two)});
select public.finalize_upload((select id from j2), ${J({ rows: 2, amount_cents: two[0].amount_cents + two[1].amount_cents })});
select is((select count(*) from public.v_recurring_candidates), 0::bigint, 'the latest export per job stands for all of it: two payroll rows, no recurring charge');
reset role;
select * from finish();
rollback;
`);
// ---- site services: the counts, the plexes, the dumpster month ------------------------------
const SS = require("../../app/site_services.js");
const SX = JSON.parse(fs.readFileSync(path.join(F, "site/expected.json"), "utf8"));
const WV = JSON.parse(fs.readFileSync(path.join(F, "site/waste_vendors.json"), "utf8"));
const sdoc = OnRent.read(fs.readFileSync(path.join(F, "site", SX.onrent)), SX.onrent);
const vocab = ["STANDARD PORTABLE RESTROOM", "HIGH RISE PORTABLE RESTROOM", "ELEVATOR FIT PORTABLE RESTROOM", "HANDICAP PORTABLE RESTROOM", "ENHANCED PORTABLE RESTROOM", "STANDARD PORTABLE RESTROOM - WOMENS",
  "PORTABLE TOILETS STANDARD", "STATIC RESTROOM - 15 STATION", "EVNT RESTROOM TRLR- 10 STATION", "RESTROOM TRAILER 12X60 RR", "RR TRAILER 12X60", "RESTROOM CONTAINER 40'", "SINK - PORTABLE", "WASTE HOLDING TANK",
  "CONTAINER 20' WASTE & WATER", "SERVICE - RESTROOM 5X WEEKLY", "3X SERVICE OF WASTE TANK HALF", "SERVICE ADA RSTRM 2X WEEKLY", "SERVICE - FRESH WATER 3X WEEKLY", "SERVICE 20' CONTAINER WASTE 2X",
  "MODULAR BLDG FAST FRONT", "MODULAR BLDG FAST MIDDLE", "MODULAR BLDG FAST REAR W/2RR", "MODULAR BLDG FAST REAR NO RR", "MODULAR FAST MIDDLE", "MODULAR BLDG MIDDLE QTS PLEX", "MODULAR BLDG FRNT QTS PLEX", "MODULAR REAR W/2RR",
  "MODULAR BLDG 4-PLEX", "8PLEX TRAILER MODULAR BUILDING", "10 PLEX TRAILER", "MODULAR BLDG 24X60 W/2-RR", "MODULAR BLDG 48X", "24X56 NO RR TRAILER CUSTOM", "OFFICE TRAILER 12X60 W/RR", "OFFICE TRAILER 10X50 W/RR",
  "GLO/OFFICE CONTAINER 8X20X8'6\"", "TRAILERS", "CONTAINER 8X40X9'6\" HI CUBE", "STORAGE TRAILER- 53'", "ROLL OFF 30 YD", "DUMPSTER 40 YARD", "OFFICE TRAILER STEPS", "4 X 4 CONTAINMENT TRAY - RESTROOM", "TRAILER HVAC",
  "TOILET SINGLE MOUNT TRAILER KIT", "TANK 6300 GAL ROLLOFF POLY TANK LINED", "TRAILER EQUIP 14'-16' 9-12K DRP DCK TNDM", "TRAILER WATER TANK 500-550 GALLON", "LIGHT TOWER VERT MAST LED TRAILER", "PRESSURE WASHER 3500 PSI ON TRAILER",
  "MODULAR SHIELD PANEL 24\" X 10'", "FENCE MODULAR 12' L X 6' H TEMPORARY PAN", "FORKLIFT HOPPER 3 YARD", "TELEHANDLER 10K 55'", ""];
const q = (v) => (v == null ? "null" : "'" + String(v).replace(/'/g, "''") + "'");
const nn = (v) => (v == null ? "null" : v);
const vocabRows = vocab.map((d) => { const c = SS.classify(d); return `(${q(d)}, ${q(c.category)}, ${q(c.kind)}, ${q(c.section || null)}, ${nn(c.stations)}, ${nn(c.per_week)}, ${nn(c.sections)}, ${q(c.size || null)}, ${nn(c.rr)}, ${nn(c.yards)})`; }).join(",\n    ");
const sdc5 = JCTD.read(fs.readFileSync(path.join(F, "site", SX.jctd)), SX.jctd);
const sRows = sdc5.rows.map((r) => ({ row_index: r.row_index, job_number: r.job_number, cost_code: r.cost_code, cost_code_name: r.cost_code_name, cat: r.cat, trans_type: r.trans_type,
  period_end: r.period_end, trans_date: r.trans_date, acct_date: r.acct_date, date_stamp: r.date_stamp, units: r.units, unit_cost_cents: r.unit_cost_cents, amount_cents: r.amount_cents,
  pay_id: r.pay_id, employee_number: r.employee_number, batch: r.batch, vendor_code: r.vendor_code, vendor_name: r.vendor_name, invoice: r.invoice, item: r.item, description: r.description }));
const cnt = SX.counts;
const wantLedger = SX.ledger.map((r) => `('${r.month}-01'::date, '${r.vendor}', ${nn(r.pulls)}, '${r.source}', ${r.ledger_lines}, ${r.ledger_cents})`).join(",\n    ");
const wantLog = SX.withLog.map((r) => `('${r.month}-01'::date, '${r.vendor}', ${nn(r.pulls)}, '${r.source}', ${r.entries}, ${r.haul_lines})`).join(",\n    ");
out("07_site_services.sql", `-- 07_site_services.sql - GENERATED by tests/db/make_db_tests.js from tests/fixtures.
-- app.classify_rental must read every word app/site_services.js reads the same way; the counts and the
-- plexes on the fixture must be the JS model's; the dumpster month takes the log over the ledger.
begin;
select plan(23);
${USERS}
${EDITOR}
create temp table vocab (d text, category text, kind text, section text, stations int, per_week int, sections int, size text, rr int, yards int);
insert into vocab values
    ${vocabRows};
select is((select count(*) from vocab v where (app.classify_rental(v.d)).category is distinct from v.category or (app.classify_rental(v.d)).kind is distinct from v.kind
  or (app.classify_rental(v.d)).section is distinct from v.section or (app.classify_rental(v.d)).stations is distinct from v.stations or (app.classify_rental(v.d)).per_week is distinct from v.per_week
  or (app.classify_rental(v.d)).sections is distinct from v.sections or (app.classify_rental(v.d)).size is distinct from v.size or coalesce((app.classify_rental(v.d)).rr, 0) is distinct from coalesce(v.rr, 0)
  or (app.classify_rental(v.d)).yards is distinct from v.yards), 0::bigint, 'classify_rental reads all ${vocab.length} words of the vocabulary as the JS does');
select public.map_vendor_job('${WS}', 'united_rentals', '${SX.jobRef}', '${SX.job}');
select public.map_vendor_job('${WS}', 'united_rentals', 'CDR-SCCI-DC4', '50-60-225121');
${record("s1", sdoc, "e")}
select is((select sum(units)::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'restroom' and kind in ('standard', 'high_rise', 'elevator_fit', 'handicap', 'enhanced', 'womens')), ${cnt.restrooms.units}, 'restroom units');
select is((select units::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'restroom' and kind = 'standard'), ${cnt.restrooms.byKind.standard}, 'standard units, from the quantities');
select is((select sum(stations)::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'restroom'), ${cnt.restrooms.stations}, 'stations on the static unit');
select is((select units::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'restroom' and kind = 'sink'), ${cnt.restrooms.sinks}, 'sinks');
select is((select max(per_week) from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'service' and kind = 'restroom'), ${cnt.restrooms.service_per_week}, 'serviced 5x weekly');
select is((select units::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'trailer' and kind = 'office' and size = '12X60' and rr = 1), ${cnt.trailers.offices["12X60 w/1 RR"]}, 'offices 12X60 with a restroom');
select is((select units::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'trailer' and kind = 'modular' and size = '24X60'), ${cnt.trailers.modular["24X60 w/2 RR"]}, 'double-wides');
select is((select sum(units)::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'storage' and kind = 'container'), ${cnt.storage.container_units}, 'storage containers');
select is((select units::int from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'accessory' and kind = 'steps'), ${cnt.accessories.steps}, 'steps are an accessory, not a trailer');
select is((select count(*) from public.v_site_services_month where job_number = '${SX.job}' and month = '2026-09-01' and category = 'dumpster'), 0::bigint, 'no dumpster on the United Rentals report');
select is((select array_agg(contract_no || ':' || complexes || ':' || coalesce(sections::text, '-') || ':' || mismatch order by contract_no) from public.v_trailer_plex_month where job_number = '${SX.job}' and month = '2026-09-01'),
  array['270000001:1:6:false', '270000002:1:4:false', '270000003:0:-:true'], 'the sleeves: a 6-plex, a 4-plex, and a front with no rear flagged');
insert into public.waste_vendors (workspace_id, pattern, bills_per_haul, haul_rate_cents, container_yd) values
  ${WV.map((v) => `('${WS}', '${v.pattern}', ${v.bills_per_haul}, ${nn(v.haul_rate_cents)}, ${v.container_yd})`).join(", ")}
  on conflict (workspace_id, pattern) do update set bills_per_haul = excluded.bills_per_haul, haul_rate_cents = excluded.haul_rate_cents, container_yd = excluded.container_yd;
create temp table j5 as select (public.begin_upload('${WS}', 'jctd', repeat('e5', 32), '${SX.jctd}', 1000,
  ${J({ period: sdc5.range, as_of: sdc5.as_of, summary: { job_number: sdc5.job_number, rows: sdc5.totals.rows, amount_cents: sdc5.totals.amount_cents } })}) ->> 'upload_id')::uuid as id;
select public.append_jctd_lines((select id from j5), ${J(sRows)});
select is((select public.finalize_upload((select id from j5), ${J({ rows: sdc5.totals.rows, amount_cents: sdc5.totals.amount_cents })}) ->> 'status'), 'recorded', 'DC5 ledger recorded');
create temp table want_ledger (month date, pattern text, pulls int, source text, ledger_lines int, ledger_cents bigint);
insert into want_ledger values
    ${wantLedger};
select is((select count(*) from want_ledger w join (public.v_dumpster_month d join public.waste_vendors v on v.id = d.waste_vendor_id)
  on d.job_number = '${SX.job}' and d.month = w.month and v.pattern = w.pattern and d.pulls is not distinct from w.pulls and d.source = w.source and d.ledger_lines = w.ledger_lines and d.ledger_cents = w.ledger_cents),
  ${SX.ledger.length}::bigint, 'from the ledger alone: a pull a line for the hauler that bills that way (a credit takes one back), spend only for the lump');
select is((select count(*) from public.v_recurring_candidates where job_number = '${SX.job}'), 0::bigint, 'the hauler''s $685 lines are not a recurring rental');
insert into public.dumpster_pulls (workspace_id, job_number, pull_date, vendor_name, container_yd, pulls, ticket_no, cost_cents) values
  ${SX.log.map((p) => `('${WS}', '${p.job_number}', '${p.pull_date}', '${p.vendor_name}', ${p.container_yd}, ${p.pulls}, '${p.ticket_no}', ${nn(p.cost_cents)})`).join(", ")};
create temp table want_log (month date, pattern text, pulls int, source text, entries int, haul_lines int);
insert into want_log values
    ${wantLog};
select is((select count(*) from want_log w join (public.v_dumpster_month d join public.waste_vendors v on v.id = d.waste_vendor_id)
  on d.job_number = '${SX.job}' and d.month = w.month and v.pattern = w.pattern and d.pulls is not distinct from w.pulls and d.source = w.source and d.entries = w.entries and d.haul_lines = w.haul_lines),
  ${SX.withLog.length}::bigint, 'with the log: it wins for the vendor and month it has entries for, the ledger count stays beside it');
select is((select log_cost_cents from public.v_dumpster_month d join public.waste_vendors v on v.id = d.waste_vendor_id where d.job_number = '${SX.job}' and d.month = '2026-08-01' and v.pattern = 'sourgum'), 479500::bigint, 'the log''s cost rides along');
insert into public.dumpster_pulls (workspace_id, job_number, pull_date, vendor_name, pulls) values ('${WS}', '${SX.job}', '2026-09-04', 'Bob''s Roll-Off', 2);
select is((select pulls from public.v_dumpster_month where job_number = '${SX.job}' and month = '2026-09-01' and waste_vendor_id is null), 2, 'a hauler Settings does not know still logs');
${VIEWER}
select is((select count(*) from public.v_site_services_month where job_number = '${SX.job}') > 0, true, 'a viewer sees the counts');
select is((select count(*) from public.v_dumpster_month where job_number = '${SX.job}' and month = '2026-08-01'), 2::bigint, 'and the dumpster month');
select is((select count(*) from public.v_trailer_plex_month where job_number = '${SX.job}' and month = '2026-09-01'), 3::bigint, 'and the plexes');
reset role;
select * from finish();
rollback;
`);
console.log("wrote supabase/tests/03_labor_parity.sql, 04_rentals_parity.sql, 05_purchases.sql, 06_jctd.sql and 07_site_services.sql");
